# Generated by Django 5.1 on 2024-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_owner_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(null=True),
        ),
    ]
