# Generated by Django 5.1 on 2024-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='list',
        ),
        migrations.AddField(
            model_name='watch_list',
            name='lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch_list_listing', to='auctions.listing'),
        ),
    ]
