# Generated by Django 5.1 on 2024-09-07 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_watch_list_list_watch_list_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid_Infor',
            fields=[
                ('bid_signed', models.FloatField(null=True)),
                ('list_bidden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listing_bid_infor', serialize=False, to='auctions.listing')),
                ('isWinner', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid_infor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.listing')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
