on:
  push:
    branches:
      - main

jobs:
  launch_jenkins_job:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    env:
      JENKINS_HOST: https://dfef-115-78-131-128.ngrok-free.app
      JENKINS_JOB: github-actions-cd
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ env.JENKINS_HOST }}/job/${{ env.JENKINS_JOB }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
